root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/"
  delay = 1000
  entrypoint = ["./tmp/main"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient  exec ./tmp/main -- --port=3333"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true # docker not pull message about files change
  poll_interval = 1000
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 3333
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
